### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by fspoettel** [startae/hagrid#65]
I do not have the time to work on Hagrid right now as my field of work has shifted unfortunately. @renatocarvalho are you willing to take over?

**Comment by renatocarvalho** [comment]
@fspoettel Yep, that would be an honor! Just let me know if you would like to provide some guidance/vision that you had for hagrid.

**Comment by fspoettel** [comment]
That is great to hear, thank you @renatocarvalho. You have full push access to the repo. If you like me to transfer repository ownership to you or your company, let me know. cheers! 🙃

**Comment by fspoettel** [comment]
As for guidance: [This new spec proposal](https://github.com/w3c/csswg-drafts/issues/1696) could be really useful for hagrid and avoid the whole `padding` and `margin` workarounds once it is implemented in all major browsers

**Comment by renatocarvalho** [comment]
@fspoettel Awesome!

> That is great to hear, thank you @renatocarvalho. You have full push access to the repo. If you like me to transfer repository ownership to you or your company, let me know. cheers! 🙃

I think it could be a good idea to transfer the repo to the @startae, only if you don't mind.

> As for guidance: This new spec proposal could be really useful for hagrid and avoid the whole padding and margin workarounds once it is implemented in all major browsers

Yes, thanks for sharing!

What about the package publication process? 

Any other instruction you would like to give?

Lastly, I'm grateful for all the effort and work you've put to Hagrid so far. Really awesome job, that helped me on so many projects. Sad to see you parting directions but great to see your care and responsibility for Open Source projects.

You rock 👊

**Comment by fspoettel** [comment]
Hey @renatocarvalho, I'll transfer ownership to startae once we figured out the transition of package ownership on npm. As for package publishing process - it is done via NPM. I can add you as a maintainer and you should have no problem publishing new versions of the package. Please provide me with the username I should add on NPM - either here or [per mail](hi@felics.me)

Cheers!

**Comment by renatocarvalho** [comment]
My username is `renatocarvalho` on NPM as well. I noticed you already added me.

**Comment by fspoettel** [comment]
getting the error:  `startae/hagrid already exists and You don’t have the permission to create repositories on startae`

**Comment by renatocarvalho** [comment]
I just deleted both repos. 

You could probably transfer to my user, I believe it will be easier.

**Comment by renatocarvalho** [comment]
It worked @fspoettel 🎉
